export const TEN_NHOM: Record<string, string> = {
  '/api-keys': 'Khoá API',
  '/absence-request-comments': 'Bình luận đơn nghỉ',
  '/absence-requests': 'Xin nghỉ',
  '/accounts': 'Tài khoản',
  '/app-configs': 'Cấu hình ứng dụng',
  '/attendance-sheet': 'Điểm danh',
  '/auth': 'Đăng nhập / xác thực',
  '/catalog': 'Danh mục bán',
  '/centers': 'Cơ sở / trung tâm',
  '/class-lessons': 'Bài của lớp',
  '/class-sessions': 'Buổi học',
  '/class-shifts': 'Ca học',
  '/class-teachers': 'Giáo viên của lớp',
  '/class-users': 'Học viên trong lớp',
  '/classes': 'Lớp học',
  '/classrooms': 'Phòng học',
  '/config': 'Cấu hình',
  '/contracts': 'Hợp đồng',
  '/courses': 'Khoá học',
  '/dashboard': 'Bảng điều khiển',
  '/districts': 'Quận/huyện',
  '/exercise-comments': 'Bình luận bài tập',
  '/files': 'Tệp',
  '/functions': 'Chức năng',
  '/health': 'Kiểm tra sống',
  '/holidays': 'Ngày nghỉ',
  '/lessons': 'Bài học',
  '/modules': 'Module',
  '/orders': 'Đơn hàng',
  '/parents': 'Phụ huynh',
  '/payment-appointment': 'Hẹn thanh toán',
  '/permissions': 'Quyền',
  '/provinces': 'Tỉnh/thành',
  '/receipts': 'Biên lai học phí',
  '/role-modules': 'Quyền theo module',
  '/roles': 'Chức danh',
  '/schedule': 'Thời khoá biểu',
  '/session-exercise-attachments': 'Tệp bài tập',
  '/session-exercise-report': 'Báo cáo bài tập',
  '/session-exercise-report-attachments': 'Tệp báo cáo bài tập',
  '/session-exercises': 'Bài tập buổi học',
  '/session-review': 'Nhận xét buổi học',
  '/session-review-criteria': 'Tiêu chí nhận xét',
  '/session-times': 'Khung giờ học',
  '/settings': 'Cài đặt',
  '/setup': 'Thiết lập lần đầu',
  '/site': 'Admin tổng',
  '/staffs': 'Nhân sự',
  '/trial': 'Đăng ký dùng thử',
  '/user-preparations': 'Chuẩn bị đầu vào',
  '/user-sessions': 'Buổi học của học viên',
  '/users': 'Học viên',
  '/version': 'Phiên bản',
  '/wards': 'Phường/xã',
  '/zalo': 'Zalo',
  '/session-packages': 'Gói buổi học',
  '/crm': 'CRM: khách hàng, cơ hội, việc cần làm',
  '/makeup': 'Dạy bù / bổ trợ',
  '/notifications': 'Thông báo',
  '/post-attachments': 'Tệp đính kèm bài viết',
  '/post-comments': 'Bình luận bài viết',
  '/post-reaction': 'Cảm xúc bài viết',
  '/posts': 'Bài viết / bảng tin',
  '/reservations': 'Bảo lưu',
  '/document-reminders': 'Nhắc nộp hồ sơ',
  '/document-types': 'Loại giấy tờ',
  '/student-documents': 'Hồ sơ học viên',
  '/support': 'Phiếu hỗ trợ',
  '/support-comments': 'Bình luận hỗ trợ',
  '/zoom': 'Lớp học online Zoom',
  '/reports': 'Báo cáo tổng hợp',
};
